# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiCli < Formula
  desc "Translate natural language into shell commands using AI"
  homepage "https://github.com/kriserickson/ai-cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kriserickson/ai-cli/releases/download/v0.1.2/ai-v0.1.2-darwin-amd64.tar.gz"
      sha256 "7a8e6017ad27519bf6a90d6c2700ca0ae9a77e17157d9bd32ecc98406374b146"

      define_method(:install) do
        bin.install "ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kriserickson/ai-cli/releases/download/v0.1.2/ai-v0.1.2-darwin-arm64.tar.gz"
      sha256 "1f32d02970b67f80457e30b74905bca2f825228f0ecbc5f6bddd44c3a0d2c206"

      define_method(:install) do
        bin.install "ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kriserickson/ai-cli/releases/download/v0.1.2/ai-v0.1.2-linux-amd64.tar.gz"
      sha256 "abdab50382b4e6f825b06e0d1f8444a91d8d545bcaed4c0801d446d7cf50bec6"
      define_method(:install) do
        bin.install "ai"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ai version")
  end
end
