# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiCli < Formula
  desc "Translate natural language into shell commands using AI"
  homepage "https://github.com/kriserickson/ai-cli"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kriserickson/ai-cli/releases/download/v0.2.2/ai-v0.2.2-darwin-amd64.tar.gz"
      sha256 "2ea0f30327b95b86a82475b9806d6445dfdbb2631e0db2de7bc4b065aabc8069"

      define_method(:install) do
        bin.install "ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kriserickson/ai-cli/releases/download/v0.2.2/ai-v0.2.2-darwin-arm64.tar.gz"
      sha256 "737efd1c7ea77d57f2360eb1299a6b6798b6612bffd424807f17f58bcd785a08"

      define_method(:install) do
        bin.install "ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kriserickson/ai-cli/releases/download/v0.2.2/ai-v0.2.2-linux-amd64.tar.gz"
      sha256 "b82142051508a4327fe6802811065f27fb6a5e461ca70667110671c152a4c508"
      define_method(:install) do
        bin.install "ai"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ai version")
  end
end
